version: '3'
services:
  skwal_frontend:
    build: ./frontend
    container_name: skwal_frontend
    links:
      - skwal_backend
    ports:
      - 5000:5000

  skwal_backend:
    build: ./backend
    container_name: skwal_backend
    ports:
      - 8001:6789
