# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Websocket CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    env:
      working-directory: ./backend

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: GitHub Action for pylint
      uses: cclauss/GitHub-Action-for-pylint@0.7.0
    
    - name: Setup
      run: pip install -r requirement.txt
      working-directory: ${{env.working-directory}}

    - name: ci
      run: pylint main.py
      working-directory: ${{env.working-directory}}
